### ISSUE TITLE
line_per_fileに+5している理由について

### ISSUE THREAD

**Issue by kajyuuen** [retarfi/language-pretraining#13]
`line_per_file: int = line_all // num_files`ではなく、`line_per_file: int = line_all // num_files + 5`である理由についてお伺いしたいです。

https://github.com/retarfi/language-pretraining/blob/ebf6b40ad7bfd6c76c415f86f41c0c35b9bab25f/train_tokenizer.py#LL39C9-L40C1

**Comment by retarfi** [comment]
分割するファイル数が`num_files`より大きくならないように、各ファイルの最低行数にマージンを設定しています。
`line_per_file: int = line_all // num_file`でも各ファイルは`line_per_file + 1`行以上含むので、こちらでも問題なく動作すると思います。

**Comment by kajyuuen** [comment]
そういう理由なんですね。ありがとうございます。
