### ISSUE TITLE
node_rankが-1のときget_indices_per_processが落ちる

### ISSUE THREAD

**Issue by kajyuuen** [retarfi/language-pretraining#14]
この行において`node_rank=-1`のとき、
https://github.com/retarfi/language-pretraining/blob/ebf6b40ad7bfd6c76c415f86f41c0c35b9bab25f/utils/trainer_pt_utils.py#L28

`indices`の長さに比べて、`expand_idx`が大きいため、落ちてしまう。
https://github.com/retarfi/language-pretraining/blob/ebf6b40ad7bfd6c76c415f86f41c0c35b9bab25f/utils/trainer_pt_utils.py#L32

**Comment by kajyuuen** [comment]
関数のはじめに
```python
node_rank = 0 if node_rank == -1 else node_rank
```
のようなコードを挿入すれば、動くと思うのですがいかがでしょうか？

**Comment by retarfi** [comment]
`node_rank`が-1の場合は以下のようにRandomSamplerを使用しますが、`node_rank != -1`かつ当該ファイルの`get_indices_per_process`を使用するケースはどういう場合でしょうか？
https://github.com/retarfi/language-pretraining/blob/ebf6b40ad7bfd6c76c415f86f41c0c35b9bab25f/utils/trainer.py#L119-L120

**Comment by kajyuuen** [comment]
`world_size`を適切な値に設定してなかったのが原因のようです。大変ご迷惑おかけしました。
一度closeさせてください。
